---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.mobius.digitaled.com
spec:
  group: mobius.digitaled.com
  names:
    kind: Tenant
    plural: tenants
    shortNames:
      - tnnt
    singular: tenant
  scope: Namespaced
  versions:
    -
      additionalPrinterColumns:
        -
          description: "The tenant ID"
          jsonPath: .spec.tenantId
          name: ID
          type: string
        -
          description: "The tenant hostname"
          jsonPath: .spec.hostname
          name: Hostname
          type: string
        -
          description: "The tenant Möbius application version"
          jsonPath: .spec.appVersion
          name: Release
          type: string
        -
          description: "The tenant Möbius UUID"
          jsonPath: .spec.uuid
          name: UUID
          type: string
        -
          description: "The tenant provisioning status"
          jsonPath: .status.prov_status
          name: Status
          type: string
        -
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                appVersion:
                  description: "The tenant Möbius application version"
                  pattern: "^[a-f0-9]+$|^20(19|2[0-9]).[0-9]+(.[0-9]+)?-((dev|rel|rc[0-9]+)-)?([a-f0-9]+)$"
                  type: string
                conn:
                  description: "The tenant's database connection settings"
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                hostname:
                  description: "The tenant hostname, usually <tenant_id>.mobius.cloud"
                  type: string
                pl:
                  description: "The tenant's private labelling settings"
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                props:
                  description: "The tenant's system property settings"
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                replicas:
                  default: 1
                  description: "How many replicas of the current tenant are to be deployed"
                  type: integer
                tenantId:
                  description: "The tenant identifier"
                  pattern: "^[a-z][a-z0-9-]{1,24}[a-z0-9]$"
                  type: string
                uuid:
                  description: "The tenant's UUID"
                  format: uuid
                  pattern: "^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89AB][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$"
                  type: string
              required:
                - tenantId
                - hostname
                - appVersion
                - uuid
                - conn
                - pl
              type: object
            status:
              properties:
                labelSelector:
                  type: string
                replicas:
                  type: integer
              type: object
              x-kubernetes-preserve-unknown-fields: true
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        scale:
          labelSelectorPath: .status.labelSelector
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
        status: {}
